### PR TITLE
Accordion for FAQs

### PR DESCRIPTION
**Pull request by juliaanholcer**
__Description:__

ng-bootstrap accordion added to fag-volunteers and faq-organizations components.

### CODE REVIEW

**Comment by weronikafelczak** [comment]
Good job Julia! :)

Just an opinion - maybe we could remove "odpowiedź" and "pytanie"? In my opinion it makes it look a bit messy (I know It was used before and that's not your "fault"). ;)

**Comment by juliaanholcer** [comment]
@weronikafelczak I totally agree that it needs to be changed (in the near future), I'm thinking about one of these:
https://fontawesome.com/icons/arrow-down?style=solid

**Comment by weronikafelczak** [comment]
@juliaanholcer It's exactly what I was thinking about. ;) Maybe after merge of this pull request we could make trivial issue about this so we won't forget about this idea. ;)

**Comment by CorneeSean** [comment]
Some more linter issues to fix, please ask somebody if possible to show you the logs if you don't see them, as there many of 'trailing whitespace' errors. I will be unreachable until the 1st of May from now on.

**Pull request merged**
