### PR TITLE
599 ng logout

### PR DESCRIPTION
**Pull request by ghost**
__Description:__

Logout user in angular.

Makefile with commands to run tests in Docker.

### CODE REVIEW

**Review by CorneeSean — CHANGES_REQUESTED** [review]
Logout part of this PR looks great to me. However, Makefile and Readme are not related at all to the logout part. I think those changes should be merged from separate PR, so please split it.

**Review by radoslawroszkowiak — APPROVED** [review]

**Comment by jacol12345** [comment]
Hey @CorneeSean! I wanted to run all tests and got really frustrated about having to exec a command inside Docker command to run tests. Creating a separate issue, separate branch and so on was a lot of fuss. I agree it is the correct way to go is to work on small issues. However, in this case the value of creating a separate ticket is marginal. I promise to do better in the future :D

**Comment by CorneeSean** [comment]
Ok, let it be for now, but remember that you can always make a new branch a cherry pick from existing one, especially that you have separate commit for that :)

**Review by CorneeSean — APPROVED** [review]

**Comment by radoslawroszkowiak** [comment]
@CorneeSean, whereas I think you are right about the `Makefile` part, I think it brings more value to actually merge it (since this part is in fact okay), than discuss it (split it, make another issues, PRs, etc.), considering the limited programming powers this project has. This project is not in the "stabilized", matured state at the moment and things (whether it's splitted or not) are way less important than delivering it quickly. Isn't it, @magul. Cheers.

**Pull request merged**
