### PR TITLE
adding django-dynamic-fixtures

### PR DESCRIPTION
**Pull request by riv2q**
__Story / Bug id:__ not story
__Reference person:__ @riv2q
__Description:__

Adding django-dynamic-fixtures to requirements
Documentation: http://django-dynamic-fixture.readthedocs.io/en/latest/overview.html
Main features: http://django-dynamic-fixture.readthedocs.io/en/latest/ddf.html

__New imports / dependencies:__

* `django-dynamic-fixtures`

### CODE REVIEW

**Comment by tomaszwozniak** [comment]
Any reason to commiting it without usage?

**Comment by riv2q** [comment]
It's relevant to comment on https://github.com/CodeForPoznan/volontulo/pull/497/files

**Comment by tomaszwozniak** [comment]
Yeah, cool, good stuff 👍

**Comment by w1stler** [comment]
I guess we could merge it. @magul, any objections? ;-)

**Pull request merged**
