### PR TITLE
543 google analytics tracking

### PR DESCRIPTION
**Pull request by w1stler**
Description: this works only on frontend pages.

### CODE REVIEW

**Comment by magul** [comment]
@CorneeSean We just spoke yesterday with @w1stler about moving this line:
```
ga('create', 'UA-XXXXXXXX-XX', 'auto'); // replace on production
```
somhow to Angular application and storing our `UA-XXXXXXX-XX` inside `environment`.

What do You think about it?

**Comment by CorneeSean** [comment]
@magul I was thinking somewhat the same thing, although I also thought that we could take care of it later on. On the other hand, if we can do it properly now that would be a plus.

As for doing it from angular,I see two solutions: either we inject the script to the page from existing top component by querying a DOM after App load or we add the script ar a link to the script to a template and prevent it from rendering with *ngIF, based on envrionmental variables. 

I am not sure though if putting scripts in templates/injecting scripts is allowed at all or by default in new Angular so we should test the solution thoroughly beforehand and connect it to a test GA account for example.

**Comment by CorneeSean** [comment]
Ok, as for Angular part I have come up and tested the following solution for injecting the script:
[https://gist.github.com/CorneeSean/42ed464ee293462be21c82ac1abe0bf0](url)

However, we should connect it to a test analytics app to see if it works. From the front-end side I don't see any reason why it wouldn't, but it would be a good sanity-check :)

**Comment by w1stler** [comment]
@CorneeSean I will check the script you've putted above. Using external library is IMO not necessary (at this point we just need simple statistics).

**Comment by magul** [comment]
Closing in favor of #840

**Pull request closed without merging**
